apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app:  postgre
    spec:
      containers:
      - name:  postgre
        image:  postgres:13.16
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POSTGRES_PASSWORD
          value: Pg1234
        - name: POSTGRES_USER
          value: ecommerce
        - name: POSTGRES_DB
          value: ecommerce
        ports:
        - containerPort:  5432
          name: postgre
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: default
spec:
  selector:
    app: postgre
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: postgre
    protocol: TCP
    port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  fakeshop
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app:  fakeshop
    spec:
      containers:
      - name:  fakeshop
        image:  ademirpereira/fake-shop:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          value: postgre
        - name: DB_USER
          value: ecommerce
        - name: DB_PASSWORD
          value: Pg1234
        - name: DB_NAME
          value: ecommerce
        - name: FLASK_APP
          value: index.py
        ports:
        - containerPort:  5000
          name: fakeshop   
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
  namespace: default
spec:
  selector:
    app: fakeshop
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
