name: CI - CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

      - run: echo "obter codigo"
      - run: echo "docker build"
      - run: echo "enviar image docker para docker hub"

  CD:
      needs: ["CI"]
      runs-on: ubuntu-latest
      steps:

      - run: echo "obter codigo"
      - run: echo "config kubernetes"
      - run: echo "excutar apply"

    
  
      
